<a href="https://colab.research.google.com/github/daurice/Linear-regression/blob/main/SingleVarLinearRegression_Salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Importing the dataset
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/session 2/salary_data.csv')

In [ ]:
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [ ]:
df.shape

(30, 2)

In [ ]:
sns.regplot(x=df.YearsExperience,y=df.Salary,ci=None)

<Axes: xlabel='YearsExperience', ylabel='Salary'>

In [ ]:
# Visualizing the Training set results
plt.scatter(df.YearsExperience,df.Salary, color='red')
#plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.title('Salary VS Experience')
plt.xlabel('Year of Experience')
plt.ylabel('Salary')
plt.show()

In [ ]:
#Linear regression model =>  y=mx+c

#get a copy of dataset exclude last column

X=df.iloc[:,0:1].values

#alternate way to initialize X

#X=df["YearsExperience"].values

In [ ]:
X=df.iloc[:,0:1].values
#X=df["YearsExperience"].values


#print X, check its data type, shape, dimension

X

type(X)

X.shape

X.ndim

In [ ]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
type(X)

numpy.ndarray

In [ ]:
X.shape

(30, 1)

In [ ]:
X.ndim

2

#get array of dataset in column 1st i.e. target column / independent feature

y=df.iloc[:, 1].values

#alternate way to initialize y

#y=df["Salary"].values

In [ ]:
y=df.iloc[:, 1].values

#print y, check its data type, shape, dimension

y

type(y)

y.shape

y.ndim

In [ ]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872])

In [ ]:
type(y)

numpy.ndarray

In [ ]:
y.shape

(30,)

In [ ]:
y.ndim


1

#Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=12)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=12 )




#Print X_train, X_test, y_train, y_test and check their shape

In [ ]:
X_train
X_train.shape

(24, 1)

In [ ]:
X_test
X_test.shape

(6, 1)

In [ ]:
y_train
y_train.shape

(24,)

In [ ]:
y_test
y_test.shape

(6,)

#Fitting Simple Linear Regression to the Training set

from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

type(model)

sklearn.linear_model._base.LinearRegression

#Train ML model using fit function

model.fit(X_train, y_train)

In [ ]:
model.fit(X_train, y_train)


LinearRegression()

In [ ]:
X_test


array([[3.2],
       [7.9],
       [5.9],
       [4.5],
       [1.3],
       [7.1]])

In [ ]:
y_test

array([ 54445, 101302,  81363,  61111,  46205,  98273])

#Predicting the Test set results

y_pred = model.predict(X_test)

y_pred

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([ 55675.5913984 , 100372.57413579,  81352.58148158,  68038.58662364,
        37606.59837691,  92764.5770741 ])

In [ ]:
y_test

array([ 54445, 101302,  81363,  61111,  46205,  98273])

In [ ]:
y_diff=y_pred-y_test
y_diff

array([ 1230.5913984 ,  -929.42586421,   -10.41851842,  6927.58662364,
       -8598.40162309, -5508.4229259 ])

In [ ]:
model.predict([[15]])

array([167893.54805821])

In [ ]:
#y=mx+c

In [ ]:
model.coef_

array([9509.9963271])

In [ ]:
model.intercept_

25243.603151676223

In [ ]:
#y=mx+c
#m-- slope--coef.
#c-- intercept

In [ ]:
model.predict([[15]])

array([167893.54805821])

In [ ]:
#model.coef_


In [ ]:
#model.intercept_

In [ ]:
#y =  m      * x +    c
y=model.coef_*15+model.intercept_
y

array([167893.54805821])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [ ]:
print("MAE test score:", mean_absolute_error(y_test, y_pred))
print("MSE test score:", mean_squared_error(y_test, y_pred))
print("RMSE test score:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("r2 test score:", r2_score(y_test, y_pred))
#adjusted r2 square

MAE test score: 3867.4744922769446
MSE test score: 25774164.367154535
RMSE test score: 5076.8262100602315
r2 test score: 0.9429269163491423
